# Generated by Django 3.2.6 on 2021-09-04 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=100, verbose_name='Наименование предмета')),
            ],
            options={
                'verbose_name': 'Наименование оборудования',
                'verbose_name_plural': 'Наименование оборудований',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_room', models.CharField(max_length=100, verbose_name='Наименование помещения')),
                ('max_people', models.IntegerField(verbose_name='Максимальное количество участников')),
                ('description_room', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_telegram', models.IntegerField(verbose_name='Телеграм')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия ')),
                ('type', models.CharField(choices=[('private_person', 'Физическое лицо'), ('company', 'Юридическое лицо')], max_length=15, verbose_name='Тип')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Организация')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('registration_date', models.DateField(verbose_name='Дата регистрации')),
                ('registration_time', models.TimeField(verbose_name='Время регистрации')),
                ('status', models.CharField(choices=[('waiting_approval', 'На рассмотрении'), ('approval', 'Одобрен'), ('not_approved', 'Отклонен'), ('deleted', 'Удален')], default=('waiting_approval', 'На рассмотрении'), max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(max_length=255, verbose_name='Наименование мероприятия')),
                ('quantity_people', models.IntegerField(verbose_name='Количество участников')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('finish_time', models.TimeField(verbose_name='Время окончания')),
                ('status_event', models.CharField(choices=[('waiting_approval', 'На рассмотрении'), ('approval', 'Одобрено'), ('active', 'Активно'), ('canceled', 'Отменено')], default=('waiting_approval', 'На рассмотрении'), max_length=20, verbose_name='Статус')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.room', verbose_name='Помещение')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Coworking_Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_slot', models.IntegerField(verbose_name='Номер слота')),
                ('quantity_people', models.IntegerField(verbose_name='Количество участников')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('finish_time', models.TimeField(verbose_name='Время окончания')),
                ('status_slot', models.CharField(choices=[('waiting_approval', 'На рассмотрении'), ('approval', 'Одобрен'), ('active', 'Активен'), ('canceled', 'Отменен')], default=('waiting_approval', 'На рассмотрении'), max_length=20, verbose_name='Статус')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.room', verbose_name='Помещение')),
                ('user_id_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user', verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Коворкинг (слот)',
                'verbose_name_plural': 'Коворкинг (слоты)',
            },
        ),
        migrations.CreateModel(
            name='Coworking_People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ф.И.О')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('status_people', models.CharField(choices=[('waiting_approval', 'На рассмотрении'), ('approval', 'Одобрен'), ('canceled', 'Отменен')], default=('waiting_approval', 'На рассмотрении'), max_length=20, verbose_name='Статус')),
                ('visited', models.BooleanField(default=False, verbose_name='Присутствовал')),
                ('slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.coworking_slot', verbose_name='Слот')),
                ('user_id_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user', verbose_name='Добавил')),
            ],
            options={
                'verbose_name': 'Коворкинг (участники)',
                'verbose_name_plural': 'Коворкинг (участники)',
            },
        ),
        migrations.CreateModel(
            name='Count_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_item', models.IntegerField(verbose_name='Количество')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.name_item', verbose_name='Наименование предмета')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.room', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Оборудования',
                'verbose_name_plural': 'Оборудования',
            },
        ),
    ]
