# Generated by Django 3.2.6 on 2021-09-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworking_slot',
            name='number_slot',
            field=models.BigIntegerField(verbose_name='Номер слота'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_telegram',
            field=models.BigIntegerField(verbose_name='Телеграм'),
        ),
    ]
