# Generated by Django 3.2.6 on 2021-09-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20210926_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworking_slot',
            name='status_slot',
            field=models.CharField(choices=[('waiting_approval', 'На рассмотрении'), ('approval', 'Одобрен'), ('active', 'Активен'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default=('waiting_approval', 'На рассмотрении'), max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status_event',
            field=models.CharField(choices=[('waiting_approval', 'На рассмотрении'), ('approval', 'Одобрено'), ('active', 'Активно'), ('completed', 'Завершено'), ('canceled', 'Отменено')], default=('waiting_approval', 'На рассмотрении'), max_length=20, verbose_name='Статус'),
        ),
    ]
