# Generated by Django 3.2.6 on 2021-09-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_event_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата бронирования'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время броирования'),
        ),
    ]
