# Generated by Django 3.2.6 on 2021-09-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20210926_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_date',
            field=models.DateField(verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_time',
            field=models.TimeField(verbose_name='Время броирования'),
        ),
    ]
