# Generated by Django 3.2.6 on 2021-09-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20210926_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status_event',
            field=models.CharField(choices=[('waiting_approval', 'На рассмотрении'), ('approval', 'Одобрено'), ('active', 'Активно'), ('completed', 'Завершено'), ('canceled', 'Отменено')], default=('waiting_approval', 'На рассмотрении'), max_length=40, verbose_name='Статус'),
        ),
    ]
