# Generated by Django 3.2.6 on 2021-09-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_event_status_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Телефон'),
        ),
    ]
