# Generated by Django 3.2.6 on 2021-10-01 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Other', 'Другое'), ('Rejected_registration', 'Отклонено в регистрации'), ('Rejected_booking', 'Отклонено в бронирование помещения'), ('Rejected_coworking_slot', 'Отклонено в бронирование коворкинг слота'), ('Rejected_coworking_human', 'Отклонено в записи на коворкинг')], default=('Other', 'Другое'), max_length=50, verbose_name='Тип')),
                ('message_from_user', models.TextField(blank=True, null=True, verbose_name='Сообщение от пользователя')),
                ('message_from_employee', models.TextField(verbose_name='Сообщение от сотрудника')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('status', models.CharField(choices=[('Pending', 'На рассмотрении'), ('Solved', 'Решено'), ('Failed', 'Неудачно')], default=('Pending', 'На рассмотрении'), max_length=20, verbose_name='Статус')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Проблема',
                'verbose_name_plural': 'Проблемы',
            },
        ),
    ]
