# Generated by Django 3.2.6 on 2021-10-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='message_from_employee',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение от сотрудника'),
        ),
    ]
