# Generated by Django 3.2.6 on 2021-10-01 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_auto_20211001_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='coworking_people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.coworking_people', verbose_name='Коворкинг (участники)'),
        ),
    ]
