# Generated by Django 3.2.6 on 2021-10-01 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_alter_connection_coworking_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='user_id',
        ),
        migrations.AddField(
            model_name='connection',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='coworking_people',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.coworking_people', verbose_name='Коворкинг (участники)'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='coworking_slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.coworking_slot', verbose_name='Коворкинг (слот)'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.event', verbose_name='Мероприятие'),
        ),
    ]
