# Generated by Django 3.2.6 on 2021-10-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_auto_20211001_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='message_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Телеграм'),
        ),
    ]
