# Generated by Django 3.2.6 on 2021-10-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_issue_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.CharField(choices=[('Other', 'Другое'), ('Notification', 'Оповещение пользователей'), ('Rejected_registration', 'Отклонено в регистрации'), ('Delete_profile', 'Удаление профиля'), ('Rejected_booking', 'Отклонено в бронирование помещения'), ('Rejected_coworking_slot', 'Отклонено в бронирование коворкинг слота'), ('Rejected_coworking_human', 'Отклонено в записи на коворкинг')], default=('Other', 'Другое'), max_length=50, verbose_name='Тип'),
        ),
    ]
