# Generated by Django 3.2.6 on 2021-12-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_historicaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_сoworking',
            field=models.BooleanField(default=False, verbose_name='Коворкинг'),
        ),
    ]
