# Generated by Django 3.2.6 on 2021-12-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_room_is_сoworking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='is_сoworking',
            new_name='is_coworking',
        ),
    ]
