# Generated by Django 3.2.6 on 2022-01-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_rename_is_сoworking_room_is_coworking'),
    ]

    operations = [
        migrations.AddField(
            model_name='coworking_slot',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата бронирования'),
        ),
        migrations.AddField(
            model_name='coworking_slot',
            name='registration_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время броирования'),
        ),
    ]
