# Generated by Django 3.2.6 on 2022-01-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_auto_20220113_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coworking_slot',
            name='number_slot',
        ),
    ]
